version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/code # Mount the entire backend directory
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000

  db:
    image: postgres:13
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
